a.out: create.c find.c insert.c LowerToUpper.c main.c prototype.h sort_name.c update_name.c update_public.c update_public_target.c
	gcc -g create.c find.c insert.c LowerToUpper.c main.c prototype.h sort_name.c update_name.c update_public.c update_public_target.c
